Require GR/GR_jll new enough to avoid precompile/loading error
Otherwise Resolver.jl-based `min=@alldeps` resolution on julia v1.9.0
chooses a version which fails to precompile with error:

```
ERROR: The following 1 direct dependency failed to precompile:

Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]

Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to "~/.julia/compiled/v1.9/Plots/jl_npbZ7Q".
ERROR: LoadError: could not load library "~/.julia/artifacts/2118fab1644a0abb3dd43fb741c68b42e8a92505/lib/libGRM.so"
libxml2.so.2: cannot open shared object file: No such file or directory
Stacktrace:
...
```