Require Plots new enough to avoid precompile error
Otherwise Resolver.jl-based `min=@alldeps` resolution on julia v1.9.0
chooses a version which fails to precompile with error:

```
ERROR: The following 1 direct dependency failed to precompile:

Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]

Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to "/home/justin/.julia/compiled/v1.9/Plots/jl_RmP7yp".
ERROR: LoadError: MethodError: no method matching joinpath(::typeof(Scratch.scratch_dir), ::String)

Closest candidates are:
  joinpath(::AbstractString...)
   @ Base path.jl:327

Stacktrace:
...
```